#!/bin/sh

############################
# Scaled Algencan
# Visit github.com/leonardosecchin/scaled-algencan
#
# This script unpacks and compiles Metis 4.0.3
# if provided by the user.
############################

echo "=============================================="
echo "Unpacking/compiling Metis 4.0.3..."
echo "=============================================="

if [ -d "metis-4.0.3" ]; then
   # metis-4.0.3 already unzipped
   if [ -s "metis-4.0.3/libmetis.a" ]; then
      # metis-4.0.3 already compiled
      echo
      echo "metis-4.0.3 library found!"
      echo "If you want to recompile Metis, run 'make clean' first."
      echo
   else
      # compile metis-4.0.3
      (cd metis-4.0.3 && make COPTIONS=-fPIC)
   fi
else
   if [ -s "metis-4.0.3.tar.gz" ]; then
      tar -zxf metis-4.0.3.tar.gz
      (cd metis-4.0.3 && make COPTIONS=-fPIC)
   else
      echo
      echo "metis/metis-4.0.3.tar.gz not found!"
      echo
   fi
fi
